@ProductCatalog.Api_HostAddress = https://localhost:7000

@id = 2

GET {{ProductCatalog.Api_HostAddress}}/api/products/
Accept: application/json

###

GET {{ProductCatalog.Api_HostAddress}}/api/products/{{id}}

###


PATCH {{ProductCatalog.Api_HostAddress}}/api/products/{{id}}/price
Content-Type: application/json

{
    "Price": 130
}

###