@ProductCatalog.Api_HostAddress = https://localhost:7000

@id = 2

GET {{ProductCatalog.Api_HostAddress}}/api/products/
Accept: application/json

###

GET {{ProductCatalog.Api_HostAddress}}/api/products/{{id}}

###

