@ProductCatalog.Api_HostAddress = https://localhost:7000

@id = 2

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2piYi5wbCIsImlzcyI6Imh0dHBzOi8vd3d3LnNhZ2VzLnBsIiwiZXhwIjoxNzU2ODExMzAwLCJqdGkiOiIzNjllZmVjOS0wNGYzLTRjMzMtOWIwYy1kYzFlYWI2NGZkOWEiLCJuYW1lIjoiam9obiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImpvaG5AZG9tYWluLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJkZXZlbG9wZXIiLCJhZG1pbiIsInRlc3RlciJdLCJiaXJ0aGRhdGUiOiIyMDA0LTA5LTAxVDIyOjAwOjAwLjAwMDAwMDBaIiwiaWF0IjoxNzU2ODExMDAwLCJuYmYiOjE3NTY4MTEwMDB9.jh-qsZSZA7GqG-8D2FNWYqug7JBjFaVMSCu7wRoM1U4

GET {{ProductCatalog.Api_HostAddress}}/api/products/
Accept: application/json
Authorization: Bearer {{access_token}}


###

GET {{ProductCatalog.Api_HostAddress}}/api/products/{{id}}
Authorization: Bearer {{access_token}}

###


PATCH {{ProductCatalog.Api_HostAddress}}/api/products/{{id}}/price
Content-Type: application/json

{
    "Price": 130
}

###