services:
  blazor.app:
    build:
      context: .
      dockerfile: Clients/Blazor.Client/Dockerfile            

  shoppingcart.api:
    build:
      context: .
      dockerfile: MicroServices/ShoppingCart/ShoppingCart.Api/Dockerfile    
    environment:
      ConnectionStrings__Connection: "redis:6379"
    depends_on:
      - redis

  productcatalog.api:
    build:
      context: .
      dockerfile: MicroServices/ProductCatalog/ProductCatalog.Api/Dockerfile    
    environment:
      ConnectionStrings__Connection: "redis:6379"
    depends_on:
      - redis

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  ordering.api:
    build:
      context: .
      dockerfile: MicroServices/Ordering/Ordering.Api/Dockerfile

  payment.api:
    build:
      context: .
      dockerfile: MicroServices/Payment/Payment.Api/Dockerfile

  identityprovider.api:
    build:
      context: .
      dockerfile: IdentityProvider/IdentityProvider.Api/Dockerfile

  yarpapigateway:
    build:
      context: .
      dockerfile: ApiGateway/YarpApiGateway/Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - shoppingcart.api
      - productcatalog.api
      - ordering.api
      - payment.api
      - identityprovider.api
      - blazor.app

volumes:
  redis-data: