@ShoppingCart.Api_HostAddress = https://localhost:7000

GET {{ShoppingCart.Api_HostAddress}}/ping
Accept: application/json

###


POST {{ShoppingCart.Api_HostAddress}}/api/cart
Content-Type: application/json
{
    "Id": 2,
    "Name": "a",
    "Price": 1.99
}

###


DELETE {{ShoppingCart.Api_HostAddress}}/api/cart
Content-Type: application/json
{
    "Id": 2,
    "Name": "a",
    "Price": 1.99
}

###